// Human-readable descriptions for table column headers.
// Shown as tooltips on hover.

export const COLUMN_DESCRIPTIONS: Record<string, string> = {
  // === PRC (OS Processes) ===
  pid: "OS process ID",
  ppid: "Parent process ID",
  name: "Process name (comm)",
  cmdline: "Full command line",
  state: "Process state (R=running, S=sleeping, D=disk wait, Z=zombie)",
  cpu_pct: "CPU usage percentage",
  mem_pct: "Memory usage as percentage of total RAM",
  vsize_kb: "Virtual memory size (total address space)",
  rsize_kb: "Resident set size (physical memory used)",
  vgrow_kb: "Virtual memory growth since last sample",
  rgrow_kb: "Resident memory growth since last sample",
  vswap_kb: "Swapped out memory",
  psize_kb: "Proportional set size (PSS)",
  vstext_kb: "Code segment size",
  vdata_kb: "Data segment size",
  vstack_kb: "Stack size",
  vslibs_kb: "Shared libraries size",
  vlock_kb: "Locked memory size",
  read_bytes_s: "Disk read throughput (bytes/s)",
  write_bytes_s: "Disk write throughput (bytes/s)",
  read_ops_s: "Disk read operations per second",
  write_ops_s: "Disk write operations per second",
  total_read_bytes: "Total bytes read (cumulative)",
  total_write_bytes: "Total bytes written (cumulative)",
  total_read_ops: "Total read operations (cumulative)",
  total_write_ops: "Total write operations (cumulative)",
  cancelled_write_bytes: "Cancelled write bytes (truncated files)",
  uid: "Real user ID",
  euid: "Effective user ID",
  gid: "Real group ID",
  egid: "Effective group ID",
  num_threads: "Number of threads",
  curcpu: "CPU core currently running on",
  nice: "Nice value (-20 to 19)",
  priority: "Scheduling priority",
  rtprio: "Real-time scheduling priority",
  policy: "Scheduling policy (0=normal, 1=FIFO, 2=RR)",
  blkdelay: "Block I/O delay (ticks)",
  nvcsw_s: "Voluntary context switches per second",
  nivcsw_s: "Involuntary context switches per second",
  minflt: "Minor page faults (no disk I/O)",
  majflt: "Major page faults (required disk I/O)",
  tty: "Terminal device number",
  exit_signal: "Signal sent to parent on exit",
  pg_query: "PostgreSQL query (if PG backend)",
  pg_backend_type: "PostgreSQL backend type (if PG backend)",

  // === PGA (pg_stat_activity) ===
  database: "Database name",
  user: "Database user name",
  application_name: "Application name set by client",
  client_addr: "Client IP address",
  wait_event_type: "Wait event type (Lock, IO, LWLock, etc.)",
  wait_event: "Specific wait event name",
  backend_type: "Backend type (client backend, autovacuum, etc.)",
  query: "Current or last executed SQL query",
  query_id: "Query identifier (from pg_stat_statements)",
  query_duration_s: "Time since current query started",
  xact_duration_s: "Time since current transaction started",
  backend_duration_s: "Time since backend connected",
  backend_start: "When this backend process started",
  xact_start: "When current transaction started",
  query_start: "When current query started",
  rss_kb: "Resident memory of backend OS process",
  stmt_mean_exec_time_ms: "Mean execution time from pg_stat_statements",
  stmt_max_exec_time_ms: "Max execution time from pg_stat_statements",
  stmt_calls_s: "Calls/s rate from pg_stat_statements",
  stmt_hit_pct: "Buffer cache hit ratio from pg_stat_statements",

  // === PGS (pg_stat_statements) ===
  queryid: "Statement identifier (hash of normalized query)",
  calls: "Total number of executions (cumulative)",
  rows: "Total rows returned (cumulative)",
  mean_exec_time_ms: "Average execution time per call",
  min_exec_time_ms: "Minimum execution time observed",
  max_exec_time_ms: "Maximum execution time observed",
  stddev_exec_time_ms: "Standard deviation of execution time",
  calls_s: "Executions per second (rate)",
  rows_s: "Rows returned per second (rate)",
  exec_time_ms_s: "Execution time consumed per second (rate)",
  shared_blks_read_s: "Shared buffer blocks read from disk per second",
  shared_blks_hit_s: "Shared buffer blocks found in cache per second",
  shared_blks_dirtied_s: "Shared buffer blocks dirtied per second",
  shared_blks_written_s: "Shared buffer blocks written per second",
  local_blks_read_s: "Local buffer blocks read per second",
  local_blks_written_s: "Local buffer blocks written per second",
  temp_blks_read_s: "Temp file blocks read per second",
  temp_blks_written_s: "Temp file blocks written per second",
  temp_mb_s: "Temp file megabytes per second",
  rows_per_call: "Average rows returned per call",
  hit_pct: "Buffer cache hit ratio (shared_blks_hit / total reads)",
  total_plan_time: "Total planning time (cumulative, ms)",
  total_exec_time: "Total execution time (cumulative, ms)",
  wal_records: "Total WAL records generated (cumulative)",
  wal_bytes: "Total WAL bytes generated (cumulative)",

  // === PGT (pg_stat_user_tables) ===
  relid: "Table OID",
  schema: "Schema name",
  table: "Table name",
  display_name: "Schema-qualified table name",
  n_live_tup: "Estimated number of live rows",
  n_dead_tup: "Estimated number of dead rows (need vacuum)",
  size_bytes: "Total table size on disk (including indexes, TOAST)",
  last_autovacuum: "Time since last autovacuum",
  last_autoanalyze: "Time since last autoanalyze",
  last_vacuum: "Time since last manual vacuum",
  last_analyze: "Time since last manual analyze",
  seq_scan_s: "Sequential scans per second",
  seq_tup_read_s: "Rows read by sequential scans per second",
  idx_scan_s: "Index scans per second",
  idx_tup_fetch_s: "Rows fetched by index scans per second",
  n_tup_ins_s: "Rows inserted per second",
  n_tup_upd_s: "Rows updated per second",
  n_tup_del_s: "Rows deleted per second",
  n_tup_hot_upd_s: "HOT updates per second (no index update needed)",
  vacuum_count_s: "Manual vacuums per second",
  autovacuum_count_s: "Autovacuums per second",
  analyze_count_s: "Manual analyzes per second",
  autoanalyze_count_s: "Autoanalyzes per second",
  heap_blks_read_s: "Heap blocks read from disk per second",
  heap_blks_hit_s: "Heap blocks found in cache per second",
  idx_blks_read_s: "Index blocks read from disk per second",
  idx_blks_hit_s: "Index blocks found in cache per second",
  tot_tup_read_s: "Total rows read per second (sequential + index)",
  disk_blks_read_s: "Total disk blocks read per second (heap + index)",
  io_hit_pct: "Buffer cache hit ratio for all I/O",
  seq_pct: "Sequential scan ratio (seq / total scans * 100)",
  dead_pct: "Dead rows ratio (dead / total tuples * 100)",
  hot_pct: "HOT update ratio (hot / total updates * 100)",
  toast_blks_read_s: "TOAST blocks read from disk per second",
  toast_blks_hit_s: "TOAST blocks found in cache per second",
  tidx_blks_read_s: "TOAST index blocks read from disk per second",
  tidx_blks_hit_s: "TOAST index blocks found in cache per second",

  // === PGI (pg_stat_user_indexes) ===
  indexrelid: "Index OID",
  index: "Index name",
  display_table: "Schema-qualified table name",
  idx_scan: "Total index scans (cumulative)",
  idx_tup_read_s: "Index entries read per second",

  // === PGL (pg_locks) ===
  depth: "Depth in lock tree (1 = root blocker)",
  root_pid: "PID of the root blocking process",
  lock_type: "Lock type (relation, transactionid, tuple, etc.)",
  lock_mode: "Lock mode (AccessShareLock, ExclusiveLock, etc.)",
  lock_target: "Lock target (table name, transaction ID, etc.)",
  lock_granted: "Whether lock is held (true) or waiting (false)",
  state_change: "Time since last state change",

  // === Schema views (client-side aggregation) ===
  tables: "Number of tables in schema",
  indexes: "Number of indexes in schema",
  unused: "Number of indexes with zero scans",
  tup_read_s: "Total tuples read per second (seq + idx)",
  ins_s: "Total inserts per second across schema",
  upd_s: "Total updates per second across schema",
  del_s: "Total deletes per second across schema",
  blk_rd_s: "Total block reads per second (heap + idx)",
  blk_hit_s: "Total block hits per second (heap + idx)",
};
