//! TUI widgets for rpglot.

mod debug_popup;
pub mod detail_common;
mod header;
mod help;
mod pga;
mod pga_detail;
mod pgi;
mod pgi_detail;
mod pgl;
mod pgl_detail;
mod pgs;
mod pgs_detail;
mod pgt;
mod pgt_detail;
pub mod prc;
mod prc_detail;
mod quit_confirm;
pub mod summary;
mod time_jump;

pub use debug_popup::render_debug_popup;
pub use header::render_header;
pub use help::render_help;
pub use pga::render_postgres;
pub use pga_detail::render_pg_detail;
pub use pgi::render_pg_indexes;
pub use pgi_detail::render_pgi_detail;
pub use pgl::render_pg_locks;
pub use pgl_detail::render_pgl_detail;
pub use pgs::render_pg_statements;
pub use pgs_detail::render_pgs_detail;
pub use pgt::render_pg_tables;
pub use pgt_detail::render_pgt_detail;
pub use prc::render_processes;
pub use prc_detail::render_process_detail;
pub use quit_confirm::render_quit_confirm;
pub use summary::{calculate_summary_height, render_summary};
pub use time_jump::render_time_jump;
